### PR TITLE
fix(ui): fix lora sort

### LINKED ISSUE #4217: [bug]: Frontend: Valid LoRAs are always displayed at bottom of popup menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2rc1

### What happened?

The LoRA selection popup menu in the linear UI reorders the list of LoRAs such that the ones that are valid in the currently selected model are always at the **bottom** of the menu rather than where you expect them to be.

See screenshots for examples, but here is what I observe:

1. If a SD-1 model is selected, then the order of sections in the LoRA menu is:
     - Stable Diffusion 2.x (all inactive)
     - Stable Diffusion XL (all inactive)
     - Stable Diffusion 1.x (all active)
 2. If a SD-2 model is selected, then the order of sections becomes:
      - Stable Diffusion 1.x (all inactive)
      - Stable Diffusion XL (all inactive)
      - Stable Diffusion 2.x (all active)
 3. If a SDXL model is selected, then you get:
      - Stable Diffusion 1.x (all inactive)
      - Stable Diffusion 2.x (all inactive)
      - Stable Diffusion XL (all active)

The consequence of this is that when the user pulls down the menu, all the LoRAs they see are inactive ones and they have to know to scroll to the bottom of the menu to see the others.

What is the expected behavior? In order of preference:
1. Only show the LoRAs that apply to the current model. Don't show the ones for other model bases.
2. Rearrange the base model sections so that the currently applicable one is at the top. So when the user selects the menu, the first thing they sees are the loras they can select. _This is how the textual inversion pulldown works_
3. Keep the order of base model sections invariant.

### Screenshots

sdxl-selected
sd-2-selected
sd-1-selected

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [s] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      

## Description

was sorting with disabled at top of list instead of bottom

fixes #4217

## Related Tickets & Documents

- Related Issue #
- Closes #4217

## QA Instructions, Screenshots, Recordings

image

### CODE REVIEW

File: invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ const ParamLoRASelect = () => {
       a.label && b.label ? (a.label?.localeCompare(b.label) ? 1 : -1) : -1
     );
 
-    return data.sort((a, b) => (a.disabled && !b.disabled ? -1 : 1));
+    return data.sort((a, b) => (a.disabled && !b.disabled ? 1 : -1));
```
Comment (blessedcoolant) [inline invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx:62]: This flips the order of the items in the group and sort them from Z-A instead of A-Z.

We need to run another sort for the group name based on which active model is selected in order to make sure the sorted list has the active model items at the top at all times.

**Review by blessedcoolant — CHANGES_REQUESTED** [review]

File: invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx (hunk 1 above)
Comment (psychedelicious) [reply invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx:62]: The model adapters already sort the models alphabetically, there's actually no need to do more sorting - removing the other sort makes it alphabetical

Comment (psychedelicious) [reply invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx:57]: Thanks for catching, fixed 
image

**Review by blessedcoolant — APPROVED** [review]
