### PR TITLE
[Fix]: UI text labels not being localized 

### LINKED ISSUE #5308: [bug]: UI text labels not being localized or missing from Weblate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.4.0post2 (main)

### What happened?

Several text labels in the UI are not converted to the related localized version, or are not available on Weblate for translation. I am reporting this relatively to the Italian localization, but this seems to happen also with other localizations.

I took screenshots of the UI highlighting the labels that don’t show up correctly for one of the two above reasons.

MAIN UI - GENERATION PARAMETERS

279465358-232c11ae-7535-4ec1-a0c3-f5d47aed0965

“Drop” is not using the localized text on Weblate.
immagine

IMAGE TO IMAGE

immagine

“No initial image selected” is not using the localized text.
immagine

The labels of the two highlighted buttons on the top right corner, “Upload Initial Image” and “Reset Initial Image”, are not available on Weblate for translation.
immagine

"Set as initial image" is not using the localized text.
immagine

In Unified Canvas, the labels for blur effects in the Compositing Settings are not available on Weblate for translation:
immagine

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by rohinish404**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Related Tickets & Documents

- Related Issue #5308
- Closes #5308

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by rohinish404** [comment]
@Harvester62 can you check if all the issues u mentioned are fixed or not. Only the last two are left from my side i'll fix that.

**Comment by Harvester62** [comment]
Sure, I can check it. I will let you know.

**Comment by rohinish404** [comment]
@Harvester62 and @psychedelicious its done now!

File: invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx [hunk 1]
```diff
@@ -126,7 +126,7 @@ const GalleryImageGrid = () => {
           loadingText={t('gallery.loading')}
           flexShrink={0}
         >
-          {`Load More (${currentData.ids.length} of ${currentViewTotal})`}
+          {`${t('accessibility.loadMore')} (${currentData.ids.length} of ${currentViewTotal})`}
```
Comment (psychedelicious) [inline invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx:129]: This isn't quite right - the word "of" will still be used. Maybe the easiest fix is to use a "/" instead?

Otherwise, we'd need to update this translation to use interpolation. But I'm not sure that the "quantity OF total" structure even exists in all languages. So I think just using a "/" is best.

**Review by psychedelicious — CHANGES_REQUESTED** [review]

File: invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx (hunk 1 above)
Comment (rohinish404) [reply invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx]: done

**Review by psychedelicious — APPROVED** [review]
Thanks!
