### PR TITLE
fix(ui): LoRA number input min/max restored

### LINKED ISSUE #8532: [bug]: Lora weights are limited to -1 / +2 [v6.6.0rc1]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Install method

Invoke's Launcher

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24GB

### Version number

v6.6.0rc1

### Browser

Edge 139.0.3405.125

### System Information

_No response_

### What happened

Lora weight values gets capped to -1 / +2. Attempts to set a value higher / lower than this gets automatically replaced with -1 / +2. Recalling lora's with weights outside this window from previously generated images works as expected until I attempt to modify the weight

### What you expected to happen

I expect it to allow weight values outside the -1 / +2 window. 

### How to reproduce the problem

1. Add a Lora
2. Manually set weight to -2
3. Observe that weight gets automatically changed to -1
4. Manually set weight to 3
5. Observe that weight gets automatically changed to 2

### Additional context

_No response_

### Discord username

_No response_

### PR DESCRIPTION
**Pull request by csehatt741**
## Summary

A new bugfix was implemented to restore LoRA weight number input min/max limits

- `DEFAULT_LORA_WEIGHT_CONFIG` values, `numberInputMin` and `numberInputMax`, were restored

## Related Issues / Discussions

Closes #8532

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ ] _❗Changes to a redux slice have a corresponding migration_
- [ ] _Documentation added / updated (if applicable)_
- [ ] _Updated `What's New` copy (if doing a release after this PR)_

### CODE REVIEW

File: invokeai/frontend/web/src/features/lora/components/LoRACard.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ const LoRAContent = memo(({ lora }: { lora: LoRA }) => {
             onChange={handleChange}
             min={DEFAULT_LORA_WEIGHT_CONFIG.sliderMin}
             max={DEFAULT_LORA_WEIGHT_CONFIG.sliderMax}
-            step={DEFAULT_LORA_WEIGHT_CONFIG.coarseStep}
+            step={DEFAULT_LORA_WEIGHT_CONFIG.fineStep}
```
Comment (psychedelicious) [inline invokeai/frontend/web/src/features/lora/components/LoRACard.tsx]: These composite input components have both `step` and `fineStep` props. `fineStep` is used when the user holds `shift`.
